// Render a Brand OS synthesis to portable Markdown.
//
// Used by the .md download button and the email body (so the coach can
// paste the whole thing into ChatGPT / Claude / Gemini and keep working
// from where Brand OS left off).

import type { BrandOsSynthesis } from "@/app/api/brand-os/synthesize/route";

export function renderSynthesisMarkdown(s: BrandOsSynthesis, opts?: { coachName?: string; completedAt?: string }): string {
  const lines: string[] = [];
  const push = (l: string) => lines.push(l);
  const blank = () => lines.push("");

  // ── Header ──────────────────────────────────────────────
  push(`# Brand OS — Deliverable`);
  if (opts?.coachName) push(`**For:** ${opts.coachName}`);
  if (opts?.completedAt) push(`**Generated:** ${opts.completedAt}`);
  blank();
  push(`> Paste this into ChatGPT, Claude, or Gemini and ask: *"Use this as my brand context for everything we work on going forward."*`);
  blank();
  push(`---`);
  blank();

  // ── Positioning ─────────────────────────────────────────
  push(`## Positioning`);
  blank();
  push(`**What you do:** ${s.positioning_line}`);
  blank();
  push(`**Signature line:**`);
  blank();
  push(`> ${s.signature_line}`);
  blank();

  // ── Voice DNA ───────────────────────────────────────────
  push(`## Voice DNA`);
  blank();
  push(`- **Tone:** ${s.voice_dna.tone}`);
  push(`- **Rhythm:** ${s.voice_dna.rhythm}`);
  blank();
  push(`**Signature moves (things AI can't fake about you):**`);
  for (const m of s.voice_dna.signature_moves ?? []) push(`- ${m}`);
  blank();
  push(`**Words & phrases you use:**`);
  push(s.voice_dna.vocab_yes?.map((v) => `\`${v}\``).join(" · ") || "_(none captured)_");
  blank();
  push(`**Words & phrases to NEVER use:**`);
  push(s.voice_dna.vocab_no?.map((v) => `\`${v}\``).join(" · ") || "_(none captured)_");
  blank();

  // ── Buyer Mirror ────────────────────────────────────────
  push(`## Buyer Mirror`);
  blank();
  push(`**Name:** ${s.buyer_mirror.name}`);
  push(`**Portrait:** ${s.buyer_mirror.one_line_portrait}`);
  blank();
  push(`**Body state at 6am Tuesday:**`);
  push(`> ${s.buyer_mirror.body_state}`);
  blank();
  push(`**The sentence they'd say at 11pm with a drink and one trusted friend:**`);
  push(`> ${s.buyer_mirror.secret_sentence}`);
  blank();
  push(`**Graveyard — what they've already tried:**`);
  push(s.buyer_mirror.graveyard);
  blank();

  // ── Pillars ─────────────────────────────────────────────
  push(`## Content Pillars`);
  blank();
  (s.pillars ?? []).forEach((p, i) => {
    push(`### ${i + 1}. ${p.name}`);
    push(`- **Why this earns the spot:** ${p.why}`);
    push(`- **Enemy (what it pushes against):** ${p.enemy}`);
    push(`- **Your proof:** ${p.proof}`);
    blank();
  });

  // ── Keywords ────────────────────────────────────────────
  push(`## Content Keywords`);
  push(`_For SEO, captions, hashtags, and topic clustering._`);
  blank();
  push((s.keywords ?? []).map((k) => `\`${k}\``).join(" · "));
  blank();

  // ── Resonance hooks ─────────────────────────────────────
  push(`## Ship This Week — 5 Content Angles`);
  blank();
  (s.resonance_hooks ?? []).forEach((h, i) => {
    push(`### ${i + 1}. ${h.headline}`);
    push(`*Pillar: ${h.pillar}*`);
    blank();
    push(h.angle);
    blank();
  });

  // ── Strengths / Gaps ────────────────────────────────────
  push(`## What's Working`);
  blank();
  push(s.what_great);
  blank();
  for (const x of s.strengths ?? []) push(`- ${x}`);
  blank();

  push(`## What to Work On`);
  blank();
  push(s.what_not);
  blank();
  for (const x of s.gaps ?? []) push(`- ${x}`);
  blank();

  // ── Next steps ──────────────────────────────────────────
  push(`## Next 7–30 Days`);
  blank();
  (s.next_steps ?? []).forEach((n, i) => {
    push(`### ${i + 1}. ${n.action}`);
    push(`- **Why:** ${n.why}`);
    push(`- **When:** ${n.when}`);
    blank();
  });

  push(`---`);
  push(`*Generated by ElevateAI Brand OS · elevateaisystem.com*`);

  return lines.join("\n");
}
